# -*- encoding: UTF-8 -*-
#    Create:  jeduardo** 17/07/2016 **  **
#    type of the change:  Creacion
#    Comments: Creacion del modulo de hr_payroll_send_email

{
    'name': 'Hr Payroll Send Email',
    'description': """\
===================================\n
\n
    It allows the electronic payment of the receipts of payment generated by payroll of the employees.
\n
===================================\n
    Elaborated by Yorman Pineda.
                   """,
    'author': 'TYSAMNCA',
    'category': 'Human Resources',
    'data': [
        'views/payslip.xml',
        'views/payslip_run.xml',
        'views/mail_template.xml',
        ],
    'depends': ['hr_payroll','mail','contacts'],
    'installable': True,
}